### ISSUE TITLE
Hijacked mouse

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#107]
OpenTomb captures mouse pointer and doesn't release it when switched to another window.

**Comment by stohrendorf** [comment]
This is because of the event handling, which doesn't get inactive when the window looses its focus, and keeps calling `SDL_WarpMouseInWindow`. As a workaround, call `cmake` with `-DCMAKE_BUILD_TYPE=Debug`, which entirely disables warping. I had this problem from the beginning, and I guess this is because of incomplete event handling routines.

**Comment by vvs-** [comment]
This is not acceptable because of #98. But it's not critical so can wait until fixed some day.
