### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#120]
We need a common build system. Or not; if everyone has their own I can live with that, too, but we need to define this somehow. 

Right now, we have a Cmake based system. I also had an Xcode project which was completely separate. So let's maybe start with a survey first: What are you currently using to build OpenTomb?

Inspired by #119

**Comment by vvs-** [comment]
Cmake on Linux. Though, you might already know that.

**Comment by stohrendorf** [comment]
Cmake everywhere.

**Comment by Gh0stblade** [comment]
I don't use CMake, I would like to try it out.... But build tutos for Windows never worked on my system and it's just too much work messing around getting things working when there's other things to be doing.

**Comment by vvs-** [comment]
Cmake is good and all, but there is a learning curve which can't be imposed. It can work only if all the developers would agree to switch to it.

**Comment by stohrendorf** [comment]
Then the question is: which other build system is available that runs on all target platforms *and* guarantees a consistent configuration? Other than cmake, I can think of SCons, which is Python based and also has a learning curve; qmake has also a learning curve and is built on Qt; there is Autotools, which honestly is very old and primarily for unix-compatible build environments, and it also has its learning curve; and then there's MPC, which is written in perl, has its own learning curve, and I honestly haven't heard of it before looking on wikipedia.

**Comment by vvs-** [comment]
The problem is that not everyone *cares* about consistency. I'm all in favor of cmake, but others might ignore it anyway. As we need to go on then we'd have no choice but live with it.

**Comment by Lwmte** [comment]
I'm using Code::Blocks and have no idea how to use CMake! There's no problem for me to switch to it, if it's not over-complicated, purposefully-crypted and geek-oriented as "Auto"-tools and friends.

Only problem is debugging, in Code::Blocks I can just push the button, build a debug version, mark breakpoints right in IDE, etc. I suppose, I'll lose this functionality when switching to CMake.

**Comment by vvs-** [comment]
> I suppose, I'll lose this functionality when switching to CMake.

No, you won't. Cmake generates native project files and supports Code::Blocks. The only thing you lose is the ability to edit that project files directly. You'll need to edit CMakeLists.txt instead and refresh Code::Block project afterwards.

**Comment by cochrane** [comment]
I'm using Cmake for the Mac version now (using the method vvs described). It was surprisingly painless, even if I won't start using it for my Mac-only projects anytime soon.

**Comment by ablepharus** [comment]
OpenTomb should decide for one build system and stick with it. Why do one job more than once? Just to introduce more ground for compiling problems that can barely be reproduced? CMake would be my choice, it is not perfect, but does everything I ever needed from a C/C++ build system. 

Pick your poison.

**Comment by vobject** [comment]
I am maintaining the CMake script since its introduction and use it to build on Windows, Linux, and for MinGW cross compilation (-> the automated builds). It's easy and convenient on Linux but sucks on Windows. However, every build system sucks on Windows. I don't think there's a huge benefit to replace it with, say SCons.

The big part of compiling OpenTomb on Windows is setting up the environment: installing MinGW, dependencies, and CodeBlocks. But once this is out of the way, the rest is a piece of cake: generate native project files (.cbp) and start editing in CodeBlocks. A few months ago I have documented the process in a video and posted it to the TR forum: https://www.youtube.com/watch?v=FrZlCmv7GRw.

So I am all for a wider adaption of CMake and the removal of CB project files from the repo.
On Windows there are some inconveniences, like no parallel build out of the box. On Linux, I use QtCreator as it allows to use the CMake script directly as project file.

Since the big merge the compilation process has changed, right? The documentation for setting up a development environment and compiling for the first time must be updated and maintained. This is essential and I feel very strongly about it. It doesn't have to be in video form, but a walk-through must exist.

**Comment by stohrendorf** [comment]
Isn't CMake the chosen build system now?

**Comment by Lwmte** [comment]
I suppose yes! :smile: I'm just waiting an answer from TeslaRus, cause he used manually-generated CodeBlocks project (which compiled faster, by the way - is there a way to make CMake generate "fast" CodeBlocks project? currently it takes lots of time to rebuild, event if I only changed one letter in one source file).

CMake is pretty neat indeed, only I wonder why SDL2/SDL2_Image doesn't use it.

**Comment by vvs-** [comment]
I believe you have misinterpreted the real cause. It's not CMake that is making "slow" projects. It's a C++ which is compiled slower than C.

**Comment by Lwmte** [comment]
No, it's certainly not some particular module compiling too slow; it's some kind of "extra" stage at the end of compilation (or linking), it's something about "linklibs", and it takes about 15 seconds to compile on my PC.

**Comment by vvs-** [comment]
It must be something Windows specific then. I don't have extra stages. All I have is compiling each source file and then link the executable at the end (4 seconds).

**Comment by stohrendorf** [comment]
Windows is always slow when it comes to disk access. I have a LaTeX project here that takes 10-15 seconds on Linux to build, but sometimes up to 5 minutes on Windows ;)

**Comment by vvs-** [comment]
As we already have seen in the audio code the file streams are unbuffered by default in Windows C runtime.

**Comment by Lwmte** [comment]
But the problem is, it happens *only* with CMake-generated project. If I use project from TeslaRus old revision, it works flawlessly fast.

**Comment by vvs-** [comment]
Then it means that there are problems in the Code::Blocks project generated by CMake. As I never used Code::Blocks on Windows, I have no idea what it might be.

**Comment by cochrane** [comment]
No longer needed, references old version of the code.
