### ISSUE TITLE
Crash in frustums

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#142]
Citing cochrane here:

> frustums crash because std::vector does not ensure proper alignment for btScalar3

**Comment by stohrendorf** [comment]
Actually, floats are *always* aligned to 4-byte boundaries, and vectors are aligned *always* aligned to 16-byte boundaries, which is ensured by the allocator. In fact, on my system the data is perfectly aligned, yet it crashes and I have no idea why.

**Comment by cochrane** [comment]
Did you _check_ that the vectors are actually aligned on 16-byte boundaries? For example, the memory address where it crashes? Because on my computer, they weren't. Surprised the hell out of me, given that the system malloc here also ensures 16-byte granularity, but I have no idea how STL uses its allocator in detail.

**Comment by stohrendorf** [comment]
Well, the only explanation I have right now is that the code is working on already free'd data, *or* there is some serious memory corruption somewhere. Nevertheless, the STL allocators take care of proper memory alignment, so if there are actually misaligned pointers, the underlying data structures (here the vector) is corrupted.

**Comment by cochrane** [comment]
Sorry to be annoying, but did you check, or did you not?

I think it's possible that you give the STL allocators too much credit. The sixteen-byte requirement for SSE types is a bit of an odd duck in the x86 (which otherwise can do everything in eight byte), and I've had more than one case where I had to set an alignment manually to get stuff working. I don't know whether standard STL allocators really know of this requirement, which does not apply to any of the usual suspects of types. If they don't, then they'll treat __m128 as a composite like a struct, and may decide that aligning that on an eight-byte boundary is okay - as it would be, in every case other than this one.

It seems the bullet developers have had similar issues; there are dedicated aligned allocator and deallocator functions (also an allocator class, which is not STL compatible, and a btAlignedObjectArray which is almost like std::vector, but misses iterators and is thus useless in practice).

I definitely had this misalignment on my computer. The btVector3 was beautifully aligned on an eight-byte boundary. The important question now is whether this is something that's only happening to me (I think I'm using a different C++ standard library from everyone else) - in that case your crash is a different bug from mine.

**Comment by stohrendorf** [comment]
Well, this bug here is a double-free corruption. I'm running valgrind in the hope to find the cause.

**Comment by vvs-** [comment]
I have such output:
```
*** Error in `./OpenTomb': double free or corruption (!prev): 0x0a2b47b8 ***
======= Backtrace: =========
/lib/libc.so.6(+0x6ce09)[0xb6bb1e09]
/lib/libc.so.6(+0x74406)[0xb6bb9406]
/lib/libc.so.6(cfree+0x56)[0xb6bbd676]
/lib/libstdc++.so.6(_ZdlPv+0x1c)[0xb6d7801c]
./OpenTomb(_ZN9__gnu_cxx13new_allocatorI9btVector3E10deallocateEPS1_j+0x11)[0x86ccf81]
./OpenTomb(_ZNSt16allocator_traitsISaI9btVector3EE10deallocateERS1_PS0_j+0x17)[0x86cae96]
./OpenTomb(_ZNSt12_Vector_baseI9btVector3SaIS0_EE13_M_deallocateEPS0_j+0x1e)[0x86c4f56]
./OpenTomb(_ZNSt6vectorI9btVector3SaIS0_EE17_M_default_appendEj+0x15a)[0x86c19ac]
./OpenTomb(_ZNSt6vectorI9btVector3SaIS0_EE6resizeEj+0x3f)[0x86be213]
./OpenTomb(_ZN7Frustum14split_by_planeERK9btVector3PSt6vectorIS0_SaIS0_EE+0x311)[0x86e0fa5]
./OpenTomb(_ZN7Frustum22portalFrustumIntersectEP6PortalRKSt10shared_ptrIS_EP6Render+0x3a4)[0x86e15b4]
./OpenTomb(_ZN6Render12genWorldListEv+0x103)[0x86efcd3]
./OpenTomb(_Z14Engine_Displayv+0x70)[0x874397b]
./OpenTomb(_Z12Engine_Framef+0xbd)[0x8743b80]
./OpenTomb(main+0x54)[0x87437b0]
/lib/libc.so.6(__libc_start_main+0xde)[0xb6b5ce7e]
./OpenTomb[0x85cf351]
```

**Comment by stohrendorf** [comment]
There are some mismatched new/free pairs, as well as some other issues I'm still tracing down.
