### ISSUE TITLE
Character::lean is broken

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#173]
The function continuously leans Lara to the right (even when she's standing), while in reality it should be engaged only on specific calls, and restore zero lean on standing.

**Comment by stltomb** [comment]
I found the cause: before the C++ refactoring, the angles Character::lean works with were normalized to fit in a  <0; 360) range. This normalization was performed in Entity::updateTransform().

The problem is that the lean function does not expect the angles to be outside of this normalized range and this statement:
```C++
m_angles[2] += ((360 - std::abs(m_angles[2]) + lean_coeff) / 2) * engine_frame_time;
```
keeps adding to the angle until it stops oscillating around the value 407.9 (the sign changes back and forth).

Adding that normalization step back fixes the issue for me.

**Comment by Lwmte** [comment]
It means that angles are *are not normalized at all*? Perhaps, it was also got lost somewhere, and I even know where. It's updateRotations function.
Thanks!

**Comment by stltomb** [comment]
Can't find any function by that name.

Anyway, all I know is this, add this piece of code:
```C++
int i = m_angles[0] / 360.0;
    i = (m_angles[0] < 0.0)?(i-1):(i);
    m_angles[0] -= 360.0 * i;

    i = m_angles[1] / 360.0;
    i = (m_angles[1] < 0.0)?(i-1):(i);
    m_angles[1] -= 360.0 * i;

    i = m_angles[2] / 360.0;
    i = (m_angles[2] < 0.0)?(i-1):(i);
    m_angles[2] -= 360.0 * i;
```
to the top of `Entity::updateTransform()` and Lara stops leaning to the right.

**Comment by Lwmte** [comment]
Well, I always wanted to rewrite this code in some way (why repeat everything three times, if we can move it to function?) so I guess I'll do it right now! :)

**Comment by vvs-** [comment]
Looks like it's a detached commit which can't be reached.

**Comment by stltomb** [comment]
Yes, I immediately deleted it once I saw that Lwmte wants to rewrite the code.

**Comment by vvs-** [comment]
Well, seems that I've just found a way to recover deleted commits on GitHub :smile:
