### ISSUE TITLE
Font antialiasing is gone

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#195]
I just noticed that fonts have jagged edges, has anybody noticed when it broke?

**Comment by stohrendorf** [comment]
This is due to the `discard` in the font fragment shader. Maybe I have "fixed" the alpha transparency too much.

**Comment by cochrane** [comment]
I don't think the font shader should have discard, it's rendered with blending anyway.

(For the record: The alpha test fix for all the other shaders looks okay. We could debate whether we should have special shaders for the alpha tested vs. non-alpha tested state, and we will probably need them once we support custom levels that use other blend modes with actual alpha values, but right now I would argue against that because it would just increase complexity a lot without helping any.)
