### ISSUE TITLE
Loading screens are not visible

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#228]
I am creating this issue as I just can't understand why it happens.
I'm using official runtime binaries from SDL website, also added PNG/JPG libs and definitions ` "-DLOAD_BMP -DLOAD_JPG -DLOAD_PNG" ` into my CMake, but it won't make a difference.

I should point out that SDL_Image produces *absolutely no errors*, i.e. file is correctly loaded, surface is correctly created, but it just don't show up.

**Comment by stltomb** [comment]
This is because the OpenGL version is now set to _3.2 core_ and there are still one or two functions or function arguments that are no longer supported by that GL version.

In this case, `glTexImage2D` can no longer take the number of color components in the texture (internalFormat) as a number.

I did something like this:
```
diff --git a/src/gui.cpp b/src/gui.cpp
index 5746bac..2d2b12d 100644
--- a/src/gui.cpp
+++ b/src/gui.cpp
@@ -1647,6 +1647,8 @@ bool gui_Fader::SetTexture(const char *texture_path)
                 texture_format = GL_RGBA;
             else
                 texture_format = GL_BGRA;
+
+            color_depth = GL_RGBA;
         }
         else if(color_depth == 3)   // No alpha channel
         {
@@ -1654,6 +1656,8 @@ bool gui_Fader::SetTexture(const char *texture_path)
                 texture_format = GL_RGB;
             else
                 texture_format = GL_BGR;
+
+            color_depth = GL_RGB;
         }
         else
         {
```

I'm not 100% sure that this is correct, but it works.

**Comment by Lwmte** [comment]
Indeed!!! Thank you SO MUCH, it works! Great job! :+1:
