### ISSUE TITLE
Missing darts

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#265]
Poisoned darts doesn't work in *Coastal Village* after recent changes.

Also, collision with darts in other levels seems to be less probable now.

**Comment by Lwmte** [comment]
Hm, that's strange. I have removed ghost objects from darts cause it was too dirty way to manage collisions anyway. Actually, ghosts never provided any collision, they only "masked" the problem with forced collision with actual dart mesh (now this problem is solved by introducing various collision type flags with respect to Bullet's own collision flags).

What about darts in TR1 and disks in TR2? Do they work?

**Comment by Lwmte** [comment]
Oh, sorry! I just forgot to change collision type for TR3 darts to GHOST.
