### ISSUE TITLE
Statement about TeslaRus engine fork

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#270]
As you probably noticed, @TeslaRus  is currently absent from master development and currently making fixes [in his own branch](https://github.com/TeslaRus/OpenTomb). It could create confusion and leave impression that he has "abandoned" master in favor of his own fork. That's not really true.

In recent conversation with him he told me that he's kinda "overwhelmed" by development speed in the main branch, and his knowledge of C++ OOP needs to be refined, as well as his coding habits needs to be changed - for this purpose, he has decided to make *experimental* changes in his fork, and based on these experiments it will be decided which structural changes to the engine are needed.

It is not clear to me, *who exactly* will decide which features from TeslaRus fork should be integrated to the main, I'm now waiting an answer from TeslaRus on this (I hope he'll also make some statements here as well).

Personally, I think this approach is risky, as (noted by @vvs-) code gets more and more diverged, files, structures and classes are renamed, which in couple with main branch rapid changes lead to complete impossibility of merging his fork with main fork. But it's his decision, and we can't change that.

**Comment by vvs-** [comment]
> It could create confusion and leave impression that he has "abandoned" master in favor of his own fork. That's not really true.

That's nice to hear.

> he's kinda "overwhelmed" by development speed in the main branch

That I can perfectly understand. The time available for review and integration of pull requests is too short. People become frustrated when they have no time to understand the changes and to avoid mistakes. We just don't have enough resources for such speed.

> Personally, I think this approach is risky

Well, we can have our opinion, but we should remember that he knows better than us. Because it's his life and his work.

**Comment by Gh0stblade** [comment]
Rather confusing, so if Tesla Rus is deciding what structural changes are required for the engine; does that mean the current refactoring changes to master *may* be reverted?

**Comment by vvs-** [comment]
I don't believe there is a justification for that. First of all it was TeslaRus who merged these changes into `master`. There was too many work put into that branch since then and nobody discouraged it. There are many bug fixes and new features that are missing from his fork. It was TeslaRus who decided to pause his development on `master`. So, he can decide how exactly he wants to integrate his recent work back into it. It won't be easy, though, and will require help from the others.

**Comment by TeslaRus** [comment]
Hi all! About my graphic: I have 30 - 90 min. a day for project. In my branch I did not need to spent time for merging, reading new code and fixing new bugs. Changes that I did is architectural, so they can be applied only manually (by coding). I will not do that in any time soon (have no time and wishes to setup environment for building master branch this time).

Ideas about refactoring: 
 - incapsulate bullet in one module and FULLY HIDE bullet functionality from engine! The code mistakes in physics will be fixed easily. Render does not need any information about bullet: UpdateRigidBody recalculates ss_bone_frame fully in dynamic body case, so You can try to delete Render_Dynamic_Body function (it was true some times ago for main branch, but...). I remove from engine code all btScalar usages. 
 - about matrices: it is better to use float[16], or may be little, easy for reading, class wrapper WITHOUT std::vector a.t.c. if OpenGL provides float[16] / double[16], then let us not to create adapters. 
  - smart pointers: tell me a reason for using that? all resources and entities are stored centralized, created and destroy centralized.  Smart pointers is a good thing (I use it on my work), but not good in engine.
It is good to read "Mcconnell Ideal code"

**Comment by T4Larson** [comment]
I just saw this, and agree with these ideas - this is the kind of decoupling that would be helpful for having a stable game loop ( #269 ) and declutter the physics-interfacing, so integrating this should imo be worth the effort...

**Comment by TeslaRus** [comment]
Example: About faders: fader is a screen effect and I suggest to move it to render module or same. Load screen (is not fader and have to stay in GUI) have to be simplified (only progress bar + background image (rect + texture index)). Bad thing if something changes in one module, and prevents to absolute other program part broke. I have some problems with custom levels loading because fader can't been started / ended correctly. This time it is fixed by Lwmte. But in many books ("Enough rope to shoot yourself in the foot", "Mcconnell Ideal code" and other) was written, that functions or modules has not been contain "hidden" effects. The screen effect does not rule game logic, the game logic have to rule screen effects.

**Comment by stohrendorf** [comment]
Hi @TeslaRus, glad to see you here again!

I fully agree with what you propose, but I have a question: You want to encapsulate everything (which is a long-term goal of at least me), but the you're proposing the exact opposite thing for OpenGL matrices. I find it good to have a wrapper when working with them, because you only pass them once to OpenGL after creating them.

**Comment by Gh0stblade** [comment]
@TeslaRus Shouldn't Inventory be moved into it's own file like Inventory.cpp? It makes GUI.cpp seem so cluttered.

**Comment by TeslaRus** [comment]
About matrices: I red (understand) something wrong... really idea is to replace
btTransform m_transform; // GL transformation matrix
by
matrix4 m_transform; // GL transformation matrix
and use matrix4 and float4 instead btTransform and btVector3 in bone frames and animation system. 
+ struct TexFrame and struct AnimSeq may be moved to polygon.h - little more logic =)

"Shouldn't Inventory be moved into it's own file like Inventory.cpp? It makes GUI.cpp seem so cluttered."
Thanks - good idea! Inventory.h exists and  we may to create inventory.cpp...

About bullet incapsulation: You can see engine_physics.h in my branch: minimal, but enough for engine needs interface. 
I.E. struct physics_data_s may be replaced by IPhysicsData class (interface class in physics.h (have no any information about bullet)) and class CPhysicsData : public IPhysicsData in physics_bullet.cpp module and fabric method.
For more easy refactoring You can start to replace btVector's and btTransform's to float4 and matrix4 (in skeletal / render / entity structures / classes fields).
