### ISSUE TITLE
Change default compiling directory

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#286]
I reported this bug earlier in VT loader refactoring section, but seems it was ignored.

I believe it is caused by moving large part of CMakeLists.txt from root directory into CMakeLists.txt in /src directory. So we either need to move it back to root script or re-define compiling directory by some CMake command, if it's possible.

**Comment by vvs-** [comment]
RUNTIME_OUTPUT_DIRECTORY

**Comment by stohrendorf** [comment]
...or you simply set the working directory to the source root without adding another hack to the CMakeLists.txt.

**Comment by Lwmte** [comment]
But it worked before, the problem was introduced by separation of CMakeLists.txt. Moreover, I have proper working directory in CodeBlocks properties, most likely it's somewhere in makefile. That's the reason why CMakeLists.txt must be edited.

**Comment by Lwmte** [comment]
By the way, RUNTIME_OUTPUT_DIRECTORY doesn't fix the problem, or I'm using it wrong. I just add this line

`set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "../")`

into CMakeLists.txt placed in /src folder.

**Comment by vvs-** [comment]
No, it's a target property. Should be set with `set_target_properties` command. And there's no `CMAKE_` prefix either.

**Comment by stohrendorf** [comment]
Then it's a CodeBlocks problem, because I'm doing an out-of-source build since I built OpenTomb the first time. And by the way, you should use `"${CMAKE_CURRENT_SOURCE_DIR}/../"` (or was it `CMAKE_CURRENT_SOURCE_DIRECTORY`?).

**Comment by vvs-** [comment]
No, I have the same problem too since the `add_subdirectory`.

**Comment by stohrendorf** [comment]
It works fine for me with QtCreator and MSVC both on Linux and Windows, so it isn't a general problem. Are you *sure* you set the executable's working directory to the source root?

**Comment by Lwmte** [comment]
Here's my CodeBlocks project options:

![clipboard-1](https://cloud.githubusercontent.com/assets/3331699/9295733/0d38c2aa-4481-11e5-9893-2bb3985fa6ad.png)

And here's where binary is placed:

![clipboard-2](https://cloud.githubusercontent.com/assets/3331699/9295734/0d3dac3e-4481-11e5-9cca-c3be2237ed6a.png)

**Comment by vvs-** [comment]
The executable is always created in the same directory level as `CMakeLists.txt` file. It's a documented behavior.

**Comment by vvs-** [comment]
```
RUNTIME_OUTPUT_DIRECTORY
       Output directory in which to build RUNTIME target files.

       This property specifies the directory into which runtime target files should be built.   Multi-configu‐
       ration generators (VS, Xcode) append a per-configuration subdirectory to the specified directory.

       There  are  three  kinds of target files that may be built: archive, library, and runtime.  Executables
       are always treated as runtime targets.  Static libraries are always treated as archive targets.  Module
       libraries are always treated as library targets.  For non-DLL platforms shared libraries are treated as
       library targets.  For DLL platforms the DLL part of a shared library is treated as a runtime target and
       the  corresponding import library is treated as an archive target.  All Windows-based systems including
       Cygwin are DLL platforms.

       This property is initialized by the value of the variable CMAKE_RUNTIME_OUTPUT_DIRECTORY if it  is  set
       when a target is created.
```

**Comment by Lwmte** [comment]
I have changed the line to this:

`set_target_properties(${PROJECT_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "../")`

Now binary is correctly placed, but it seems working directory is not set correctly, as engine can't find scripts subdirectory. Funny that in CodeBlocks build options I have correct working directory.

**Comment by vvs-** [comment]
Shouldn't it be "../.."? Usually, I just move the executable up two directory levels and don't change anything in project file.

**Comment by stohrendorf** [comment]
Referring from the first result I clicked in google, you have to set the executable working directory under "Project -> Properties -> Build targets -> [name of target] -> Execution working dir". I *think* that label there refers to the $MAKE program when called, not to executing the executable itself.

**Comment by stohrendorf** [comment]
And here's a screenshot of where to find it: http://www.ogre3d.org/tikiwiki/tiki-download_file.php?fileId=2075&display

**Comment by Lwmte** [comment]
I just thought that whole point and purpose of CMake is to *automatically generate* project files and ease life for developers, so we just open it and compile, and everything is cool. With current setup, I need to go into options, select build target and manually change paths. What's the benefit of CMake, if I can simply manually setup the CodeBlocks project?

I think that if there is no other way except `RUNTIME_OUTPUT_DIRECTORY`, which is not working for me for the reasons I described above, we should merge CMakeLists.txt back. Or make `RUNTIME_OUTPUT_DIRECTORY` solution working.

P.S.: Besides, I have proper execution working dir in CodeBlocks. And still, executable is put in the wrong folder.

**Comment by stohrendorf** [comment]
The executable isn't in the wrong folder, you're using CMake the wrong way. First of all, CMake strongly discourages in-source builds; do a `mkdir build && cd build && cmake ..` instead. Second, when you build something with cmake, it's properly built. You *can* force CMake to build everything like it should be installed later, but that's not the way it should be, because this way you can build an executable, test it, create a package, and boom, the package doesn't work because you have implicit dependencies that aren't covered when doing an out-of-source build. Third, there is a difference between build directory and working directory. Start a console, go to the source dir, and execute i.e. `./build/src/opentomb.exe`: the working directory is where you CD'd to, and the build directory is `./build/src`. Fourth, this is no flaw of CMake itself, for the reason that it's a *build* tool, not a *run* tool. If you can't configure your IDE properly, it's your problem, because other projects don't seem to have a problem at all with this. You're obviously doing something wrong in the settings, because if CodeBlocks isn't able to set the working directory, the whole IDE is lacking a core feature; and if that's the case, then switch to another IDE like QtCreator.

And what does your execution directory look like? Is it relative, or is it absolute? As you can't be sure where the *default* working dir is, it's always safer to set an absolute path.

**Comment by Lwmte** [comment]
So basically, you're telling me that everything worked perfectly before your CMakeLists.txt split is a pure coincidence? And best solution is to swich IDE? Thank you, but no.

What about @vvs- ? It's also his problem? And he also needs to change something in his settings? But I suppose he doesn't use CodeBlocks at all.

You may say it's my problem, but I was happy the way it worked before. Now I'm not. And because of this, it should be fixed.

**Comment by stohrendorf** [comment]
It should be fixed on your side, because CMake isn't the problem. And I'm not saying you should switch your IDE, I'm saying that you should configure it properly. Choose the target, set the working directory of the executable to whatever you want, and it will be fine. And the fact that you are confusing the working dir, the build dir, and the executable path supports my thought that you should learn how to use your IDE.

I'd suggest the following: Create a clean repo clone, do a `mkdir build` in it, `cd` to it, and do a `cmake ..` call in it, so that the whole project is configured *out of source*. Open your project, build it, and set the targets' execution working dir to the source root as shown in http://www.ogre3d.org/tikiwiki/tiki-download_file.php?fileId=2075&display. This *will* work, unless you do something wrong.

**Comment by stohrendorf** [comment]
And here are two screenshots proving that out-of-source builds work perfectly with two different IDEs, two different toolchains and two different project types on Windows:

![ot-msvc](https://cloud.githubusercontent.com/assets/7853507/9296923/2d1fe8e4-4497-11e5-85b1-7bfb1d18265a.png)
![ot-qtcreator](https://cloud.githubusercontent.com/assets/7853507/9296924/2d235344-4497-11e5-8bc6-e8af711e7e16.png)

And by the way, QtCreator uses CodeBlocks project files internally, so this isn't a CodeBlocks project file problem.

**Comment by stohrendorf** [comment]
Guess what? It works. And I only had to change one single tiny setting.
```
sto@linux-623b:~/devel/OpenTomb/cb-build> cmake -G "CodeBlocks - Unix Makefiles" ..
[snip]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sto/devel/OpenTomb/cb-build
```

![tr-cb-run2](https://cloud.githubusercontent.com/assets/7853507/9301119/5adcba3e-44cc-11e5-94b6-8786a89ce8f2.png)

**Comment by vvs-** [comment]
> What about @vvs- ? It's also his problem? And he also needs to change something in his settings? But I suppose he doesn't use CodeBlocks at all.

Well, I don't consider that a real problem for me. I use CLI so there is no problem with setting a working directory. After splitting CMakeLists the executable is built one directory level deeper than before. And I just need to move it up yet one level. Of course, because you are using an IDE, it requires a valid working directory and I'm not familiar with Code::Blocks to say anything about that.

**Comment by Lwmte** [comment]
Ok, I guess I'm the only one who doesn't like the way it is.

Of course, you can call me ignorant and that I need to "learn how to use my IDE", but now there's an *extra step* which needs to be done every time I re-generate project with CMake. I can live with this, but most likely someone else will eventually stumble upon this as well.

**Comment by stohrendorf** [comment]
That is a needed extra step, because the current CMake layout of OpenTomb has evolved over time so it "just works", because noone ever did a full maintenance of it. The correct way to specify the data search dir would be to have an `add_definitions(-DDATA_DIR=...)` that specifies a *relative* path from the OpenDir *build* or *install* directory to the data dir, and then do something like `rootPath = getDir(argv[0]) + DATA_DIR` in the `main()` function to specify the data dir independent of the working dir.

**Comment by Lwmte** [comment]
You mean directory in which all game resources are placed? This can be very handy (and somewhat related to #188). I think we can use this as a command-line parameter (currently OpenTomb lacks *any* command-line options, which is kinda silly).

We can even feed engine with *native* game directories at start-up, and it will use these paths to load game resources. However, it may require major rearrange of script files and may cause some problems if level names are equal for different game versions (e.g. HOUSE.TR2), so additional thought must be put into this.

OR! Even better solution - specify game paths directly in config file! This way we can just point an engine to absolute game paths without any extra command-line stuff. This can be also used in future with installer, which will only need to modify config rather than copying whole /data folder (however, we still need to solve cases with loading screens).
