### ISSUE TITLE
Missing sound samples

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#287]
Some sounds produce `SYSWARN_AS_NOSAMPLE`, e.g. 293 in TR4. Nevertheless they are used in `flipeffects.lua` (introduced in 30a225035c24fd5e412bc0ac45799a256518c3a2).

**Comment by Joey79100** [comment]
293 is marble footstep. In some early TR4 demo, it was used in the Great Library's main room, however I don't recall ever hearing it in the retail version. Probably Core kept it assigned in the level(s) while removing it from the level files, same way they did for the bubbles.

**Comment by vvs-** [comment]
Then why keep it in the flipeffects script for this game version? It just produce tons of warnings and nothing else. The same goes for bubbles, they exist only in TR1/2.

**Comment by Joey79100** [comment]
Both are used by some custom levels, so maybe it's better to keep them? Or find a way to stop this kind of errors if they have already been printed once for the level?

**Comment by Lwmte** [comment]
Yes, I occasionally hear marble footsteps in custom levels, that's why this entry was left in the first place.

Moreover, as noted by @Joey79100, there are lots of other cases of "non-existing" sound samples being triggered for particular animations and game events - like infamous "underwater door" opening sound for bleeding cases.

**Comment by vvs-** [comment]
I believe that OpenTomb should have support only for retail levels in its scripts. Authors of custom levels should have their own version instead. Actually, it's impossible to support every custom level because they could even conflict with each other. And it's very unusual to have warnings or errors because of a stuff that doesn't even exist in official Tomb Raider.

**Comment by Lwmte** [comment]
It's currently done exactly as in retail version of TR4. As I already pointed out, there are lots of cases where engine calls non-existing samples, and function just returns false, if no corresponding SoundDetails are found. This is completely normal and expected behaviour.

As far as official Tomb Raider is concerned, here is a snippet of disassembly of Flipeffect 32 for you:

```
CPU Disasm

Address   Hex dump          Command                                         Comments

004377F1  |.  66:8B47 02    MOV AX,WORD PTR DS:[EDI+2]                      Load sector material
004377F5  |.  8BC8          MOV ECX,EAX
004377F7  |.  83E1 0F       AND ECX,0000000F                                Clamp to 15 (max.)
004377FA  |.  66:83F9 06    CMP CX,6                                        Ignore stone sound
004377FE  |.  74 31         JE SHORT tomb4.00437831
00437800  |.  66:83F9 05    CMP CX,5                                        Ignore water sound
00437804  |.  74 2B         JE SHORT tomb4.00437831
00437806  |.  66:83F9 0B    CMP CX,0B                                       Ignore concrete sound
0043780A  |.  74 25         JE SHORT tomb4.00437831
0043780C  |.  8B0D 1CE08000 MOV ECX,DWORD PTR DS:[tomb4.lp_LaraPointer]     Load Lara's  pointer
00437812  |.  83E0 0F       AND EAX,0000000F                                Clamp to 15 (max.)
00437815  |.  33D2          XOR EDX,EDX
00437817  |.  83C1 40       ADD ECX,40                                      Point to Lara's pos
0043781A  |.  8A90 3CBF4A00 MOV DL,BYTE PTR DS:[EAX+tomb4.4ABF3C]           !! Load sample ID from table
00437820  |.  56            PUSH ESI
00437821  |.  81C2 20010000 ADD EDX,120                                     Add 288 to sample ID
00437827  |.  51            PUSH ECX
00437828  |.  52            PUSH EDX
00437829  |.  E8 126C0200   CALL tomb4.snd_PlaySample
0043782E  |.  83C4 0C       ADD ESP,0C
```

And here is the sample lookup table:

```
CPU Dump
Address   Hex dump                                         
004ABF3C  00 05 03 02 | 01 09 09 04 | 06 05 03 09 | 04 06 00 00 | 
```

As you can see, there *are* values of 5 for IDs 1 (snow) and 9 (marble). It means that effect ID 293 (288+5) is called for either snow or marble sector material. In my flipeffect implementation, snow ID is ignored for TR4, as snow and marble IDs are conflicting in TR3, resulting in snow footsteps in Lara's bathroom or Area 51 operating room. Other than that, everything is pretty much "official" and "genuine".

However, this made me think I need to implement "error reporting" config option in the same way as with logging, and disable it by default, so nobody will be bothered by redundant error messages.

Or - another solution - completely remove error reporting in case if called sample ID is -1, cause it basically means that non-existing SoundDetails entry was used, and function should quit silently.
