### ISSUE TITLE
Move TRosettaStone 3 out of OpenTomb master branch?

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#396]
It's a bit weird now to have this document bundled with OpenTomb code, as it's also used and updated by @XProger, who's primarily active with OpenLara project.

So my proposal is to move TRosettaStone 3 repository one level up, into "root" of OpenTomb project. This way we wouldn't need to keep whole OpenTomb source code along with documentation. And also, code updates and documentation updates won't mix up.

**Comment by vvs-** [comment]
I think that's reasonable. And you are qualified for this job ;)

**Comment by Lwmte** [comment]
I've created empty TRosettaStone3 repository, also tried to "split" /doc subfolder from main repository into it, but had some problems with renaming branches... So scrapped and recreated empty one; I guess I'll wait when my and @zdimension pull requests will be merged, and only then I'll actually split it.

**Comment by vvs-** [comment]
> On second thought, does it worth splitting? We have lost whole history when TeslaRus branch became new master. It'll be much easier just to create new repo.

I can't imagine that it'd be possible to "split" history between different repositories containing absolutely unrelated work. Just remove it and create new files from scratch. If you need an old history you should just use the old repo.

**Comment by Lwmte** [comment]
There's even a tutorial on github on how to split a subfolder into new repo preserving whole history. Only problem that I had is my branch wouldn't rename to "master", but there shouldn't be any problems if our current branches would be merged :)

**Comment by vvs-** [comment]
```
WARNING! The rewritten history will have different object names for all the objects and will not converge with the original branch. You will not be able to easily push and distribute the rewritten branch on top of the original branch. Please do not use this command if you do not know the full implications, and avoid using it anyway, if a simple single commit would suffice to fix your problem.
```
Why would we need that? The clean start would suffice.

**Comment by Gh0stBlade** [comment]
Yeah well, these are problems induced because of clear violation of source control rules (i.e not sticking to one codebase and making use of rollback features). Had the current master initially been just a roll-backed refactored old master then we wouldn't have needed to do a force push in the first place (resulting in loss of history in the master repo). Had that of been possible, we could have preserved most of TRRosettaStone 3.0 history in the master branch if it had been present at the time work began from an old version of the engine.

Though I'm 50/50 on having the documentation in the OpenTomb repo, I struggle to understand why you think it should be moved to a separate one. You have valid points in regards to having commits mixed with both documentation and code changes. Sometimes there are cases where new findings result in need of changing both anyway.

Some rules need to be enforced in regards to touching the documentation and also formatting guidelines.

Cheers.

**Comment by Lwmte** [comment]
I just think it will look cleaner if we'll have separate repos for actual engine and documentation.

**Comment by vvs-** [comment]
Sure bisecting would be easier without TRS commits.
