### ISSUE TITLE
Lua & Compiling Warning / But no error

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#481]
[100%] Linking CXX executable OpenTomb
HERE:
extern/lua/liblua5.3.a(loslib.c.o) : of the function « os_tmpname » :
loslib.c:(.text+0x177): warning : the use of `tmpnam' is dangerous, better use `mkstemp'

[100%] Built target OpenTomb

and .exe not created after compiled

for more detail:
- OS: Ubuntu 1.7.10 "Last Version"
- libpng12-dev errored i define libpng-dev no error but is the principal reason of exe not created ?

EDIT: 1.7.10 is bugged for compiling, need 16.04 for working and libpng12 is only v16.xx.

**Comment by vvs-** [comment]
This is not an error. This is just a warning that you have used incorrect compiler flags and Lua library didn't use POSIX API because of that. This can't be the cause that linker didn't produce an executable. In fact the executable is always built in the same directory that contains other CMake build artifacts, i.e. in `build` subdirectory if you have followed README.

P.S. Just noticed that README might contain an obsolete information as it doesn't mention the recommended workflow, where you should create `build` subdirectory and invoke cmake and make commands there.

**Comment by TokyoSU** [comment]
Yes i see, is a warning and compiling is working on ubuntu 16.04 not 1.7.10.
i see for the build folder but the warning is here too.
it's just a report for warning lua compilation.

**Comment by vvs-** [comment]
Yes, I can confirm that the proper way to compile Lua on Linux is to pass `LUA_USE_POSIX` flag to compile. The recomended way is to even pass `LUA_USE_LINUX` but that would actually fail without adding libdl as well. That's one of the consequences of building Lua library in-tree without complex CMake build script.

**Comment by TeslaRus** [comment]
Unfortunately I forgot to delete second file with main function from lua...
