### ISSUE TITLE
Opening Inventory or picking up items causes crash

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#62]
Opening the Inventory causes a complete crash.

**Comment by cochrane** [comment]
There's also a crash when picking up an item, which I'm assuming is caused by the same thing. This has turned out to be dependent on the graphics driver (it crashes e.g. on Nvidia but not Intel), and mine (provided by Apple) seems to be one that doesn't crash here.

It's a bug either way, no matter what the graphics driver does, it's just kind of difficult to debug like this…

**Comment by Gh0stblade** [comment]
Strange how you don't have these issues. I have an AMD card which crashes if it helps.

**Comment by vvs-** [comment]
I have Intel GMA3000 and it doesn't crash. Hope it helps.

**Comment by Gh0stblade** [comment]
Ok, I just checked your newest commit Cochrane and I no longer get crashes. If anyone else still gets crashes reopen this. Now closing.

**Comment by vvs-** [comment]
Just to draw attention to the fact that only those who closed the issue or have write privileges could reopen it.
