### ISSUE TITLE
Lara can't be resurrected anymore

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#75]
Something is broken in debug keys after ragdoll changes. If Lara dies she can't be resurrected by Z-key. She immediately drowns on land instead.

**Comment by Lwmte** [comment]
This should be fixed in e227e76.
Also note that you won't be able to re-activate death ragdolls after Lara was resurrected. This happens because resurrection is unexpected engine behaviour - and ragdoll task expects death to happen only once, after which ragdoll setting function destroys itself. In the future, gameflow should restart level, if Lara is dead.

**Comment by vvs-** [comment]
That's not a problem. It can be always reactivated by `addTask`.
