### ISSUE TITLE
Overlapped entity and static mesh

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#93]
In *Natla's Mines* entity 2 is overlapped with static mesh which is rendered as a weird double boat.

**Comment by vvs-** [comment]
After turning switch 41 there is now two separate boats instead of this "catamaran".

**Comment by vvs-** [comment]
Seems that the duplicate entity is used only for the camera showing the animation sequence.

**Comment by Lwmte** [comment]
Yeah, the setup is pretty complicated. There is "fake" boat made with one solid sector and two statics, and this setup is repeated (although in different place) in alternate room. When boat is activated, alternate room flips out of camera sight, and "real" boat entity is activated, making it visible and moving backwards (with - surprise! - accel set to -1 in anim properties). 

Most interesting is what happens with the "real" boat entity after the activation. We don't see the animation ending, as camera cuts back to Lara. I suppose it's hardcoded to disappear after it finishes its animation. Funny, because they could just use *die* animcommand. Hardcoding things which could be made data-driven out of the box seemed to be bad habit of Core Design programmers since the very first Tomb Raider.

**Comment by vvs-** [comment]
Something weird is going on with that boat. It was overlapped in `backuip` branch and now it's separate in `master`. But according to fexinspect it should be overlapped.
